### ISSUE TITLE
Issue with woocommerce.php

### ISSUE THREAD

**Issue by grich89** [BraftonSupport/braftonium#110]
https://docs.woocommerce.com/document/template-structure/

"If your theme has a woocommerce.php file, you will be unable to override the woocommerce/archive-product.php custom template in your theme, as woocommerce.php has priority over other template files. This is intended to prevent display issues."

Is this file needed? Can it be deleted? I am trying to customize that file for my site. Thanks!

**Comment by yvonnetse** [comment]
removed!
