### ISSUE TITLE
No PHP or JS notices.

### ISSUE THREAD

**Issue by yvonnetse** [BraftonSupport/braftonium#73]
Have a valid DOCTYPE declaration and include language_attributes.
Validate and/or sanitize untrusted data before entering into the database. All untrusted data should be escaped before output. (See: Data Validation)
No removing or modifying non-presentational hooks.

Provide a unique prefix for everything the Theme defines in the public namespace, including options, functions, global variables, constants, post meta, etc. Theme nav menu locations and sidebar IDs are exceptions.

**Comment by dking3876** [comment]
@yvonnetse please tag this appropriately as you have for other issues.
