### ISSUE TITLE
Plugin Dependency

### ISSUE THREAD

**Issue by allanjames** [BraftonSupport/braftonium#8]
As the theme requires the Advanced Custom Fields plugin for its options pages, this plugin will need to be bundled correctly with the theme.  Wordpress throws one warning and one fatal error on theme activation if that plugin does not exist in the destination install.

Here is one option for dependency management:
https://github.com/TGMPA/TGM-Plugin-Activation

An alternative would be to use Wordpress native meta fields.  I have taken this approach with a custom theme I am developing.

**Comment by allanjames** [comment]
Yvonne, I'll handle this one.  Going to port a new branch to the repository and test this functionality locally.

**Comment by yvonnetse** [comment]
Themes cannot require plugins to work.!!!!
https://make.wordpress.org/themes/handbook/review/required/#plugins
