### ISSUE TITLE
Add cart svg

### ISSUE THREAD

**Issue by grich89** [BraftonSupport/braftonium#96]
Add a new svg for a shopping cart icon.

**Comment by grich89** [comment]
// icon for svg-icons.svg
<symbol id="icon-cart" viewBox="0 0 24 24"><title>cart</title>
<path fill="currentColor" d="M10 19.5c0 .829-.672 1.5-1.5 1.5s-1.5-.671-1.5-1.5c0-.828.672-1.5 1.5-1.5s1.5.672 1.5 1.5zm3.5-1.5c-.828 0-1.5.671-1.5 1.5s.672 1.5 1.5 1.5 1.5-.671 1.5-1.5c0-.828-.672-1.5-1.5-1.5zm1.336-5l1.977-7h-16.813l2.938 7h11.898zm4.969-10l-3.432 12h-12.597l.839 2h13.239l3.474-12h1.929l.743-2h-4.195z"/></path>
</symbol>

// function for braftonium.php
/**
 * Add the shopping cart svg to any menu item with the cart class
 * */	
function braftonium_be_cart_icon( $item_output, $item, $depth, $args ) {
	if( in_array( 'cart', $item->classes ) ) {
		$icon = '<span>'.braftonium_get_svg_path('icon-cart').'</span>';
		$item_output = str_replace( '</a>', $icon . '</a>', $item_output );
	}
	return $item_output;
}
add_filter( 'walker_nav_menu_start_el', 'braftonium_be_cart_icon', 10, 4 );

**Comment by yvonnetse** [comment]
added!
